Step: step-credential-initializer-z7h55:

{"level":"warn","ts":1565625026.1660995,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1565625026.1664724,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
Step: step-working-dir-initializer-j4hz4:

{"level":"warn","ts":1565625027.6278803,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1565625027.6452093,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source /workspace/source/charts/anothertest\""}
Step: step-place-tools:

Step: step-git-source-bots4you-jenkins-anothertest-ma-hsbh9:

{"level":"warn","ts":1565625041.0699525,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1565625042.663781,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/Bots4You-Jenkins/anotherTest.git @ v0.0.2 in path /workspace/source"}
Step: step-git-merge:

WARNING: no SHAs to merge, falling back to initial cloned commit
Step: step-setup-**-git-credentials:

Generated Git credentials file /workspace/xdg_config/git/credentials
Step: step-build-python-unittest:


----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Step: step-build-container-build:

[36mINFO[0m[0000] Downloading base image python:onbuild        
2019/08/12 15:50:46 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:onbuild        
2019/08/12 15:50:48 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Executing 3 build triggers                   
[36mINFO[0m[0002] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0002] Checking for cached layer 10.247.208.105:5000/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
2019/08/12 15:50:49 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0002] Using files from context: [/workspace/source] 
[36mINFO[0m[0002] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0002] cmd: EXPOSE                                  
[36mINFO[0m[0002] Adding exposed port: 8080/tcp                
[36mINFO[0m[0002] Skipping unpacking as no commands require it. 
[36mINFO[0m[0002] Taking snapshot of full filesystem...        
[36mINFO[0m[0002] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0002] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0002] Taking snapshot of files...                  
[36mINFO[0m[0002] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0002] Found cached layer, extracting to filesystem 
[36mINFO[0m[0002] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] COPY . /usr/src/app                          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt .                      
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] ENV PORT 8080                                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] EXPOSE 8080                                  
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] ENTRYPOINT ["python"]                        
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] CMD ["app.py"]                               
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
2019/08/12 15:50:50 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2019/08/12 15:50:50 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2019/08/12 15:50:50 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2019/08/12 15:50:50 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2019/08/12 15:50:50 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2019/08/12 15:50:50 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2019/08/12 15:50:50 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2019/08/12 15:50:50 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2019/08/12 15:50:50 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2019/08/12 15:50:50 pushed blob: sha256:60745340ab309e89a86ce042e0a1e66ad42c412182b0a8e446c53d2ae60468ec
2019/08/12 15:50:50 pushed blob: sha256:ff840009383861572c1af900eb6cbd3ddacd69caee0cef453e5062f409614d57
2019/08/12 15:50:50 pushed blob: sha256:d54339d71edec9e2f2dd4af58d13df39295639fdba8685fc158dda97501a477e
2019/08/12 15:50:50 pushed blob: sha256:20525c386ddd3a973c9d18a33ce6ed5af26bfd28d967b6c9470e2ab585018991
2019/08/12 15:50:50 pushed blob: sha256:374c9f5c362b894a92e5578f86ad52fef7f01864dc2c4726ccff2a9e27826285
2019/08/12 15:50:50 10.247.208.105:5000/bots4you-jenkins/anothertest:0.0.2: digest: sha256:1004a61df562ce1dbd9c6c1c403e84595e121ecfecd621cc14e6c55cc1ae28c4 size: 2385
Step: step-build-post-build:

no CVE provider running in the current ** namespace so skip adding image to be analysed
Step: step-promote-changelog:

Converted /workspace/source/charts/anothertest to an unshallow repository
Generating change log from git ref 4ac3ef424f016ffc864dffe73f1bc91492ab7a45 => 68be53c19da94ca70ba15e7ace71942b891f268f
Associating user x-0 in users.jenkins.io with email heimel@bots4you.de to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit be4029a05bc22fb680202ed6692b8d3e487b1eac with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email heimel@bots4you.de to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit be4029a05bc22fb680202ed6692b8d3e487b1eac with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
WARNING: No release found for Bots4You-Jenkins/anotherTest and tag v0.0.2 so creating a new release
Updated the release information at https://github.com/Bots4You-Jenkins/anotherTest/releases/tag/v0.0.2
generated: /workspace/source/charts/anothertest/templates/release.yaml
Created Release anothertest-0-0-2 resource in namespace **
Updating PipelineActivity bots4you-jenkins-anothertest-master-2 with version 0.0.2
Updated PipelineActivities bots4you-jenkins-anothertest-master-2 with release notes URL: https://github.com/Bots4You-Jenkins/anotherTest/releases/tag/v0.0.2
Step: step-promote-helm-release:

WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file anothertest-0.0.2.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}
Step: step-promote-**-promote:

WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app anothertest version 0.0.2 to namespace **-staging
WARNING: Waiting for the fork of *******************/environment-batglen-staging to appear...
error: pulling environment repo https://github.com/Bots4You-Jenkins/environment-batglen-staging.git into /builder/home/.**/environments: failed to fork GitHub repo Bots4You-Jenkins/environment-batglen-staging to user *******************: gave up waiting for Repository *******************/environment-batglen-staging to appear: GET https://api.github.com/repos/*******************/environment-batglen-staging: 404 Not Found []
